[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "photon-hal"
version = "0.1.0"

[dependencies]
cty = "0.1.5"
static-ref = "0.1.0"

[dependencies.photon-core]
git = "https://github.com/japaric/photon-core"
